### ISSUE TITLE
develop checklist for post-submission steps

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-incubator/organization#2]
some initial thoughts:

- [ ] create a team for each lesson
- [ ] make sure that the original authors have "Admin" access to this team so they can control collaborators [1]
- [ ] add team to collaborators of the repo with "Maintain" access [2]
- [ ] check that the lesson uses remote theme, and convert it if it does not
- [ ] add the website URL to the repository description
- [ ] assign GitHub topics for the repository (at a minimum: 'lesson', life-cycle stage)
- [ ] switch to standard Carpentries set of GitHub labels

[1] this needs to be discussed further but seems that it provides the appropriate level of privilege lesson authors would expect
[2] same as above

**Comment by tobyhodges** [comment]
@fmichonneau can you clarify what is meant by "remote theme" here?

**Comment by tobyhodges** [comment]
...and with my next click, I think I got it https://github.com/carpentries-incubator/introduction-to-conda-for-data-scientists/pull/19

**Comment by fmichonneau** [comment]
yes, this is it.

**Comment by tobyhodges** [comment]
Adding to François' suggestions above:

* [ ] create a team for each lesson
* [ ] make sure that the original authors have "Admin" access to this team so they can control collaborators
* [ ] add team to collaborators of the repo with "Maintain" access
* [ ] check that the lesson uses remote theme, and convert it if it does not
* [ ] add the website URL to the repository description
* [ ] assign GitHub topics for the repository (at a minimum: 'lesson', life-cycle stage) **& update [sheet of currently-used tags](https://docs.google.com/spreadsheets/d/1KkmBtCu4PaNb5nzJAD82UHcfHQlaPY84qPVxw8WO8es/edit?usp=sharing)**
* [ ] switch to standard Carpentries set of GitHub labels
* [ ] **contact main developer(s) to discuss support, plans for lesson**
* [ ] **if appropriate, provide info to Comms Team to mention addition of lesson in next newsletter, on social media channels, etc**
* [ ] **invite developer(s) to join `incubator-developers` TopicBox list**
